### ISSUE TITLE
Module Tested on OxygenOS 13.0 ✅

### ISSUE THREAD

**Issue by tkj94** [Keinta15/Magisk-iOS-Emoji#13]
Module working well with OnePlus 11 (OxygenOS - CPH2449 - A.09)
[tested on: GBoard, WhatsApp, Facebook Messenger, Snapchat, Instagram]

Need to delete all [/data/fonts/files/{random gibberish characters}] before flashing

**Comment by clickkz** [comment]
> Module working well with OnePlus 11 (OxygenOS - CPH2449 - A.09)
> [tested on: GBoard, WhatsApp, Facebook Messenger, Snapchat, Instagram]
> 
> Need to delete all [/data/fonts/files/{random gibberish characters}] before flashing

i am on oxygen os 13.1 oneplus 10 pro and it didn't work for me when I flashed so I should be getting rid of these? ![Screenshot_2023-06-10-11-20-13-74_db51e592e420a9871f4a37915a68789b.jpg](https://github.com/Keinta15/Magisk-iOS-Emoji/assets/103363724/c0880b09-34e4-4e68-a82b-660dd6b2df2a)
