### ISSUE TITLE
Possible Zygote loop

### ISSUE THREAD

**Issue by Oreeeee** [Keinta15/Magisk-iOS-Emoji#2]
When I installed the module, my phone got stuck on my ROM logo. Checking Magisk logs showed multiple "Restarting Zygote" messages, removing the module (```/data/adb/modules/``` is the directory where Magisk stores its modules if you are stuck) fixed the issue.

Android: 12.1
ROM: ArrowOS GAPPS
Phone: Xiaomi Mi 9T (Global)
Magisk version: 25.2
Module version: v15.4.5

**Comment by Keinta15** [comment]
Module hasn't been fully tested on Android 12.1, once I get some personal issues sorted I'll take a look into it

**Comment by Keinta15** [comment]
Added Android 12 support on v15.4.6
