### ISSUE TITLE
iOS 17 Update

### ISSUE THREAD

**Issue by emowpee** [Keinta15/Magisk-iOS-Emoji#25]
I hope there will be an ios 17 emojis soon. There's kind of a lot of new emojis added.

**Comment by 5thofjuly** [comment]
+1

**Comment by CarLoOSX** [comment]
+1

**Comment by DealsBeam** [comment]
I'm hoping we can get 17.x.x emojis as well

**Comment by marcocancarini** [comment]
+1

**Comment by Keinta15** [comment]
Check [latest release](https://github.com/Keinta15/Magisk-iOS-Emoji/releases/tag/v17.4)
