### ISSUE TITLE
Stop working after sometime 

### ISSUE THREAD

**Issue by icezach** [Keinta15/Magisk-iOS-Emoji#26]
When I flashed it was working then I removed and reflashed and still not working then I reset phone and root again then I flashed and it started working again and again after sometime it stopped working.

ROM: RUI4.0
Device: Realme 10 Pro Plus

**Comment by AIMBOT312** [comment]
What I did that fixed this issue was delete the /data/fonts folder.

**Comment by Keinta15** [comment]
Try deleting all files under /data/font/files/(Random folder name), or like AIMBOT312 suggested.
