### ISSUE TITLE
Works perfectly on Android 14

### ISSUE THREAD

**Issue by alph4Smev** [Keinta15/Magisk-iOS-Emoji#28]
👍😊

**Comment by devnoname120** [comment]
I confirm that it works perfectly both in the interface and in Gboard. Doesn't work in the Google Chrome app but it might just hardcore its own emojis.

**My config**::
- Xiaomi Mi Note 10 Lite
- Android 14
- PixelOS_toco-14.0-20231218-0026
- Magisk Alpha 6cda6c2f-alpha (26403)

**Comment by rainrlyme** [comment]
crashes applications and the keyboard, but on Android 11 it didn’t crash for me

Realme 9i
Android 14
RMX3491_11_F.11
26.4-kitsune (26400)
