### ISSUE TITLE
My emojis didn't change

### ISSUE THREAD

**Issue by SharkBoy69-CS** [Keinta15/Magisk-iOS-Emoji#3]
It was working but it's not working anymore for 2 days. How could I reset the module or uninstall and reinstall ?
![Screenshot_20220913-221852_Google.jpg](https://user-images.githubusercontent.com/58356637/190001451-4951f236-f3f6-42af-92ff-b0757fce7403.jpg)

**Comment by 0xJX** [comment]
Did this happen after updating gboard? I noticed that I had some issues after doing that, I cleared the folders inside /data/fonts/files/ and rebooted. That fixed it for me. Android 12

If you want to "reset" the module:
You can delete the module via modules section, reboot and install it again to reinstall it.

**Comment by SharkBoy69-CS** [comment]
> Did this happen after updating gboard? I noticed that I had some issues after doing that, I cleared the folders inside /data/fonts/files/ and rebooted. That fixed it for me. Android 12

Yes, it could be this, but I have nothing in /data/fonts/files/. Should I reset datas of Gboard ?

**Comment by SharkBoy69-CS** [comment]
Nevermind, it worked just after clearing Gboard's data with lucky patcher (I don't know if it works directly from the system settings). Thank you very much !
