### ISSUE TITLE
new release 17.4

### ISSUE THREAD

**Issue by liukliukliuk** [Keinta15/Magisk-iOS-Emoji#32]
hi, thanks again for your work. could you please update the emojis with 17.4 release? thanks

**Comment by bugreportion** [comment]
> could you please update the emojis with 17.4 release?

You can use [my own fork.](https://github.com/bugreportion/Magisk-iOS-Emoji) There is an updated version.

**Comment by dtingley11** [comment]
> > could you please update the emojis with 17.4 release?
> 
> You can use [my own fork.](https://github.com/bugreportion/Magisk-iOS-Emoji) There is an updated version.

@bugreportion hello sir! I used your fork on ksu (overlayfs) the only problem is that it causes my apps to be detected (momo detects magisk somehow?!) and Microsoft intune company portal also detects root so I cannot use it :( However, I used this other module that replaces fonts and does not need huskydg's overlayfs module: (https://github.com/WSTxda/Mi-Lan-Font-Module) I believe that if you remade the module to be more like this it would work with kernelsu. Is that a possibility?

**Comment by bugreportion** [comment]
Oops, I just saw your comment, sorry for the delay.
In that case use attached regular version without `overlayfs` prefix. There's also [additional workaround](https://github.com/HuskyDG/magic_overlayfs#kernelsu-problem) for HuskyDG's overlayfs module specific for KernelSU, it might help you. Momo will detect abnormally mounted partition until you [change fs mode to read-only locked.](https://github.com/HuskyDG/magic_overlayfs#change-overlayfs-mode)

**Comment by dtingley11** [comment]
> @dtingley11 Oops, I just saw your comment, sorry for the delay.
> > module that replaces fonts and does not need huskydg's overlayfs module
> 
> In that case use attached regular version without `overlayfs` prefix. 
> 
> There's [additional workaround](https://github.com/HuskyDG/magic_overlayfs#kernelsu-problem) for HuskyDG's overlayfs module specific for KernelSU, it might help you. Momo will detect abnormally mounted partition until you [change fs mode to read-only locked.](https://github.com/HuskyDG/magic_overlayfs#change-overlayfs-mode)

@bugreportion Thanks for the follow up. I used the regular version without overlayfs and that one just doesn't work. I was able to fork the original repository and fix some of the code myself so that it would work with kernelsu. Maybe you could take a look and add those changes in your repo so we don't need mine, as my code is a little janky 😂

**Comment by bugreportion** [comment]
@dtingley11 Hey, not sure you even need this now, however my fork got update. I've tested emoji module working, including replacing of emoji for FB/Messenger on my devices with KernelSU. So yours should be fine too now.

**Comment by bugreportion** [comment]
No problem.

**Comment by Keinta15** [comment]
Perfect, will be closing down this issue this the original issue got resolved.

**Comment by dtingley11** [comment]
@Keinta15 sounds good. Thanks!
