### ISSUE TITLE
Emoji didnt change

### ISSUE THREAD

**Issue by Umberto1973** [Keinta15/Magisk-iOS-Emoji#4]
Hey Guys, i'm new in GitHub. My issue ist that the Emoji didnt change after  installing and rebooting. For example in Snapchat they didn't change:/
So I'm currently on a Custom ROM on the 8 Pro. Any guesses why it didn't work🤔
Thanks in advance

**Comment by Keinta15** [comment]
It didn't change only for Snapchat or overall? I don't use Snapchat, does it use custom emojis?

**Comment by Umberto1973** [comment]
In Gboard it did change, but typing it in Snapchat it still shows the android stock emojis.
I'm on the Corvus ROM for the OnePlus 8 Pro.
Where can I see if Snapchat uses custom emojis🤔

**Comment by Keinta15** [comment]
@Umberto1973 By any chance, do you have Snapchat on your Denylist?

**Comment by Umberto1973** [comment]
Yeah I got it on m deny list and cleared the cache, but it didn't work, maybe ist an A12 thing...

**Comment by Keinta15** [comment]
@Umberto1973 for Emoji's to work on Snapchat, Snapchat needs to be removed from the DenyList

**Comment by Umberto1973** [comment]
Oh I thought it has to be in the deny list. Wait, what deny list are we talking about? The one from magisk right🤔

**Comment by Keinta15** [comment]
Yep the one in Magisk
