### ISSUE TITLE
Works on OneUI 3.1 KNOX 3.7 A11 MAGISK 25.2

### ISSUE THREAD

**Issue by rmuxe** [Keinta15/Magisk-iOS-Emoji#41]
Works perfectly 
Device : 
Samsung A40(stock rom)
Magisk 25.2

Video link  : https://drive.google.com/file/d/1-njeMUlK5CHfPDd_lO-uXZQY3mMtmLlZ/view?usp=drivesdk

**Comment by rmuxe** [comment]
https://github.com/Keinta15/Magisk-iOS-Emoji/assets/169527984/af8c2b94-49b4-4357-8de0-d6fd4995d80e

**Comment by rmuxe** [comment]
.

**Comment by cuynu** [comment]
then close this, an test must be not in issues

**Comment by rmuxe** [comment]
> then close this, an test must be not in issues

I didn't know how to report that it works
