### ISSUE TITLE
This module not replacing the emojis in WhatsApp 🥲

### ISSUE THREAD

**Issue by geomonus** [Keinta15/Magisk-iOS-Emoji#42]
This module not replacing the emojis in WhatsApp 🥲

**Comment by Keinta15** [comment]
WhatsApp uses their own emoji

**Comment by fann22** [comment]
hello, i found this emojis.oba file inside the apk, which i guess contain all emojis for whatsapp
but i didn't found any information on how to unpack it

**Comment by Keinta15** [comment]
> hello, i found this emojis.oba file inside the apk, which i guess contain all emojis for whatsapp
> but i didn't found any information on how to unpack it

I do know [WA Enhancer LSPosed module](https://github.com/Dev4Mod/WaEnhancer) has an option to disable the Whatsapp emojis using that emojis.oba and instead use the system emojis. If you have the iOS module installed it'll work on WhatsApp.

**Comment by fann22** [comment]
> > hello, i found this emojis.oba file inside the apk, which i guess contain all emojis for whatsapp
> > but i didn't found any information on how to unpack it
> 
> I do know [WA Enhancer LSPosed module](https://github.com/Dev4Mod/WaEnhancer) has an option to disable the Whatsapp emojis using that emojis.oba and instead use the system emojis. If you have the iOS module installed it'll work on WhatsApp.

Thanks for the information.
Yes, it removes WhatsApp's default emojis, but somehow the emojis didn’t change to iOS emojis as expected
it changed to something,... different...
