### ISSUE TITLE
Magisk Version

### ISSUE THREAD

**Issue by Zarnnonly** [Keinta15/Magisk-iOS-Emoji#57]
Please update the module to support 27005+ version

**Comment by Keinta15** [comment]
What error are you getting?

**Comment by Keinta15** [comment]
Fixed for the next release [b8339eb](https://github.com/Keinta15/Magisk-iOS-Emoji/commit/b8339eb2a38d0876d2c8d640329e517816ced6ce)

**Comment by Keinta15** [comment]
Added a pre release [version](https://github.com/Keinta15/Magisk-iOS-Emoji/releases/tag/v17.4.1) that adds support for Magisk 27005+
