### ISSUE TITLE
Replacing iOS TTF file with a custom one

### ISSUE THREAD

**Issue by ShishirModi** [Keinta15/Magisk-iOS-Emoji#8]
Hi!
This is the first font changer module I've come across that seems to support Samsung Devices. (I haven't tried it out yet as I don't want iOS emojis).
I was wondering if I could just change up the TTF file with one that I do want and if it would work the same way. There's shouldn't be any issues, right?
Any help is appreciated!

**Comment by Keinta15** [comment]
If its a TTF file for emojis, yeah, you would just need to rename it to NotoColorEmoji.ttf and replace it. You can edit the module.prop and delete the updateJson line so it doesnt update in magisk with mine

**Comment by Keinta15** [comment]
Closing issue - if you have any doubts let me know
