### ISSUE TITLE
Module Tested on OneUI 5.0 ✅

### ISSUE THREAD

**Issue by phlexian** [Keinta15/Magisk-iOS-Emoji#9]
Module working well with S22Ultra (OneUI 5.0 - S908B) except Telegram app

`[tested on:
GBoard, WhatsApp, Facebook Messenger, Snapchat, Instagram]`

**Comment by PROxZIMA** [comment]
POCO X3 Pro Android 13 (CrDroid custom rom)

Works super fine on all applications and all emojis are fine except this one: 🫡

![Screenshot_20230216-195131_Firefox](https://user-images.githubusercontent.com/43103163/219390646-57858d9b-3811-4438-a6e4-900055d31466.png)
